source "https://rubygems.org"

gem "addressable"
gem "middleman", "~> 4.3.6"
gem "middleman-autoprefixer"
gem "middleman-blog"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-syntax", ">= 3.2.0"
gem "middleman-gh-pages"
gem "redcarpet"
gem "pry"
